name: New Feature
description: New feature.
title: "[New Feature]: "
labels: ["enhancement"]
assignees:
  -
body:
  - type: markdown
    attributes:
      value: |
          New feature idea plz.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: New feature idea
    attributes:
      label: New feature idea
      description: Tell us, your unique idea.
      placeholder: hogehoge
      value: "hogehoge"
    validations:
      required: true
