name: learn-github-actions # githubリポジトリ上のアクションタブに表示される名前
run-name: ${{ github.actor }} is learning GitHub Actions # ワークフロー実行一覧に表示されう名前。
on: [push] # トリガー
jobs: # ジョブをグループ化する。
  check-bats-version: # ジョブ1
    runs-on: ubuntu-latest
    steps: # ステップをグループ化する
      # リポジトリをランナーにチェックアウトすることで実行できる。
      - uses: actions/checkout@v3

      # nodeとnpmを使えるようにする
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
